### PR TITLE
Revision A

### LINKED ISSUE #2: Real-time Clock Support
We'd like to be able to use the RTC peripheral. I think all this will take is a battery, but I'm not sure.

### PR DESCRIPTION
**Pull request by dkitzman**
Resolves #2, #3, #5, #7, #8, #11

### CODE REVIEW

**Comment by adwranovsky** [comment]
The clock on the SDRAM isn't hooked up to anything (EPI0S31). There's an EPI0S131 on the tm4c where EPI0S31 should be.

**Comment by adwranovsky** [comment]
Also, the module is called EPI "zero", not EPI "oh".

**Comment by adwranovsky** [comment]
A note should be put on the schematic that the EPI CLK GPIO pin should be configured for 12 mA drive current. EPI Data can be configured for 8 mA.

**Comment by adwranovsky** [comment]
SB_to_UART.sch:  There's two resistors on the reset pullup network without reference designators.
EDIT: Nothing on this page has a refdes

**Comment by adwranovsky** [comment]
Reset circuit on the TM4C page doesn't have refdeses.

**Comment by adwranovsky** [comment]
R14 on the tm4c page has a resistance value of 49.4 ohms, when it should probably have a value of 49.9 ohms.

**Comment by adwranovsky** [comment]
When the tm4c wake pin isn't used it should be connected to GND, although not connecting it is acceptable. See table 26-7 in the tm4c129 datasheet.

**Comment by adwranovsky** [comment]
I'm reasonably confident that we will be able to use the NAND chip with
    the QSSI peripheral. As an added precaution I think we should add
    do-not-place pullup resistors to ~WP and ~HOLD, and a weak (around 100k-1M
    ohm) pulldown to CLK. Put a note on the schematic that says the CLK series
    resistor should be put next to the tm4c chip. I'm not entirely sure that
    the quad serial part will work, but only because TI doesn't provide the
    endianness/timing diagrams for the quad serial mode, and I didn't see any
    text describing the ordering. We will at the very least be able to use
    single data line transfers as it is currently configured though.

**Comment by adwranovsky** [comment]
Add proper decoupling to VCC on the FT232R. See page 20 of the [datasheet](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf). A single 0.1uF capacitor on VCCIO is probably sufficient, but should be added. Also consider adding TX and RX LEDs to CBUS0 and CBUS1 respectively

**Comment by adwranovsky** [comment]
Are the pullups for ~INHIBIT, ~SYSRESET, and ~ENABLE going on the backplane?

**Comment by adwranovsky** [comment]
EPI trace capacitance must be less than 35 pF. Take note of this when doing layout.

**Comment by adwranovsky** [comment]
After you address the couple issues I put above, I think it's ready to go. Here are the other things I looked at:

- VBAT
- Ethernet termination

For the future, I think we should consider adding ESD protection on pins that go to external connectors.

**Comment by dkitzman** [comment]
> ```
> Put a note on the schematic that says the CLK series
> resistor should be put next to the tm4c chip. 
> ```
What clk series resistor are you referring to here? I certainly don't have one on the NAND circuit. Am I supposed to?

**Review by adwranovsky — APPROVED** [review]
All requested changes were applied. Good to merge.

**Pull request merged**
